# @package _global_

defaults:
  - _self_
  - datamodule: default
  - module: vit_s_16
  - trainer: imagenet_vit_s_16
  - logger: null
  - callbacks: null
  - paths: default
  - extras: default
  - hydra: eval
  - codecarbon: null
  - experiment: null
  - hparams_search: null
  - debug: null
  - override /module: metaformer_hybrid_s12

# TODO Write your team name
team_name: "TODO"
tags: ["baseline", "evaluate"]

seed: 0

trainer:
  precision: 16-mixed

module:
  compile: false

checkpoints: [
  "baseline/2026-06-23/16-24-34/checkpoints/last.ckpt",
]
